name: salesiq_mobilisten
description: Mobilisten enables you to give your users the best in-app live chat experience. Mobilisten provides drop-in in-app chat and knowledge base.
version: 6.5.1
repository: https://github.com/zoho/salesiq-mobilisten-flutter/tree/main/packages/mobilisten
homepage: https://mobilisten.io/
documentation: https://www.zoho.com/salesiq/help/developer-guides/flutter-sdk-installation.html

environment:
  sdk: ">2.17.0 < 4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  salesiq_mobilisten_core: "^0.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.zohosalesiq.plugin
        pluginClass: MobilistenPlugin
      ios:
        pluginClass: MobilistenPlugin
